// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'877fcad92ade1e630a5212392e67f526a44e975f333981c014f2e43b588bfc4a'>;
export type ExecutionHash =
  ExecutionHashBase<'42d0a824dd93e54f40403b4e620cc9351729d260348e0ec38df9c3fe72f8bf3e'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Categoria: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly descricao: CodecTypes['pg/text@1']['output'] | null;
      readonly activo: CodecTypes['pg/bool@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly actualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly ItemVenda: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly vendaId: CodecTypes['pg/int4@1']['output'];
      readonly produtoId: CodecTypes['pg/int4@1']['output'];
      readonly quantidade: CodecTypes['pg/int4@1']['output'];
      readonly precoUnitario: CodecTypes['pg/numeric@1']['output'];
      readonly subtotal: CodecTypes['pg/numeric@1']['output'];
    };
    readonly MovimentoStock: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly produtoId: CodecTypes['pg/int4@1']['output'];
      readonly utilizadorId: CodecTypes['pg/int4@1']['output'];
      readonly tipo: 'ENTRADA' | 'SAIDA' | 'AJUSTE';
      readonly quantidade: CodecTypes['pg/int4@1']['output'];
      readonly stockAnterior: CodecTypes['pg/int4@1']['output'];
      readonly stockPosterior: CodecTypes['pg/int4@1']['output'];
      readonly motivo: CodecTypes['pg/text@1']['output'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Produto: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly codigo: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly descricao: CodecTypes['pg/text@1']['output'] | null;
      readonly categoriaId: CodecTypes['pg/int4@1']['output'];
      readonly precoCompra: CodecTypes['pg/numeric@1']['output'];
      readonly precoVenda: CodecTypes['pg/numeric@1']['output'];
      readonly stockActual: CodecTypes['pg/int4@1']['output'];
      readonly stockMinimo: CodecTypes['pg/int4@1']['output'];
      readonly activo: CodecTypes['pg/bool@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly actualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Utilizador: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly palavraPasse: CodecTypes['pg/text@1']['output'];
      readonly perfil: 'ADMINISTRADOR' | 'ATENDENTE';
      readonly activo: CodecTypes['pg/bool@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly actualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Venda: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly utilizadorId: CodecTypes['pg/int4@1']['output'];
      readonly total: CodecTypes['pg/numeric@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Categoria: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly descricao: CodecTypes['pg/text@1']['input'] | null;
      readonly activo: CodecTypes['pg/bool@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly actualizadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly ItemVenda: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly vendaId: CodecTypes['pg/int4@1']['input'];
      readonly produtoId: CodecTypes['pg/int4@1']['input'];
      readonly quantidade: CodecTypes['pg/int4@1']['input'];
      readonly precoUnitario: CodecTypes['pg/numeric@1']['input'];
      readonly subtotal: CodecTypes['pg/numeric@1']['input'];
    };
    readonly MovimentoStock: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly produtoId: CodecTypes['pg/int4@1']['input'];
      readonly utilizadorId: CodecTypes['pg/int4@1']['input'];
      readonly tipo: 'ENTRADA' | 'SAIDA' | 'AJUSTE';
      readonly quantidade: CodecTypes['pg/int4@1']['input'];
      readonly stockAnterior: CodecTypes['pg/int4@1']['input'];
      readonly stockPosterior: CodecTypes['pg/int4@1']['input'];
      readonly motivo: CodecTypes['pg/text@1']['input'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Produto: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly codigo: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly descricao: CodecTypes['pg/text@1']['input'] | null;
      readonly categoriaId: CodecTypes['pg/int4@1']['input'];
      readonly precoCompra: CodecTypes['pg/numeric@1']['input'];
      readonly precoVenda: CodecTypes['pg/numeric@1']['input'];
      readonly stockActual: CodecTypes['pg/int4@1']['input'];
      readonly stockMinimo: CodecTypes['pg/int4@1']['input'];
      readonly activo: CodecTypes['pg/bool@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly actualizadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Utilizador: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly palavraPasse: CodecTypes['pg/text@1']['input'];
      readonly perfil: 'ADMINISTRADOR' | 'ATENDENTE';
      readonly activo: CodecTypes['pg/bool@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly actualizadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Venda: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly utilizadorId: CodecTypes['pg/int4@1']['input'];
      readonly total: CodecTypes['pg/numeric@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly categoria: {
      readonly activo: CodecTypes['pg/bool@1']['output'];
      readonly actualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly descricao: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
    };
    readonly itemVenda: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly precoUnitario: CodecTypes['pg/numeric@1']['output'];
      readonly produtoId: CodecTypes['pg/int4@1']['output'];
      readonly quantidade: CodecTypes['pg/int4@1']['output'];
      readonly subtotal: CodecTypes['pg/numeric@1']['output'];
      readonly vendaId: CodecTypes['pg/int4@1']['output'];
    };
    readonly movimentoStock: {
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly motivo: CodecTypes['pg/text@1']['output'] | null;
      readonly produtoId: CodecTypes['pg/int4@1']['output'];
      readonly quantidade: CodecTypes['pg/int4@1']['output'];
      readonly stockAnterior: CodecTypes['pg/int4@1']['output'];
      readonly stockPosterior: CodecTypes['pg/int4@1']['output'];
      readonly tipo: 'ENTRADA' | 'SAIDA' | 'AJUSTE';
      readonly utilizadorId: CodecTypes['pg/int4@1']['output'];
    };
    readonly produto: {
      readonly activo: CodecTypes['pg/bool@1']['output'];
      readonly actualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly categoriaId: CodecTypes['pg/int4@1']['output'];
      readonly codigo: CodecTypes['pg/text@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly descricao: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly precoCompra: CodecTypes['pg/numeric@1']['output'];
      readonly precoVenda: CodecTypes['pg/numeric@1']['output'];
      readonly stockActual: CodecTypes['pg/int4@1']['output'];
      readonly stockMinimo: CodecTypes['pg/int4@1']['output'];
    };
    readonly utilizador: {
      readonly activo: CodecTypes['pg/bool@1']['output'];
      readonly actualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly palavraPasse: CodecTypes['pg/text@1']['output'];
      readonly perfil: 'ADMINISTRADOR' | 'ATENDENTE';
    };
    readonly venda: {
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly total: CodecTypes['pg/numeric@1']['output'];
      readonly utilizadorId: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly categoria: {
      readonly activo: CodecTypes['pg/bool@1']['input'];
      readonly actualizadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly descricao: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
    };
    readonly itemVenda: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly precoUnitario: CodecTypes['pg/numeric@1']['input'];
      readonly produtoId: CodecTypes['pg/int4@1']['input'];
      readonly quantidade: CodecTypes['pg/int4@1']['input'];
      readonly subtotal: CodecTypes['pg/numeric@1']['input'];
      readonly vendaId: CodecTypes['pg/int4@1']['input'];
    };
    readonly movimentoStock: {
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly motivo: CodecTypes['pg/text@1']['input'] | null;
      readonly produtoId: CodecTypes['pg/int4@1']['input'];
      readonly quantidade: CodecTypes['pg/int4@1']['input'];
      readonly stockAnterior: CodecTypes['pg/int4@1']['input'];
      readonly stockPosterior: CodecTypes['pg/int4@1']['input'];
      readonly tipo: 'ENTRADA' | 'SAIDA' | 'AJUSTE';
      readonly utilizadorId: CodecTypes['pg/int4@1']['input'];
    };
    readonly produto: {
      readonly activo: CodecTypes['pg/bool@1']['input'];
      readonly actualizadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly categoriaId: CodecTypes['pg/int4@1']['input'];
      readonly codigo: CodecTypes['pg/text@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly descricao: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly precoCompra: CodecTypes['pg/numeric@1']['input'];
      readonly precoVenda: CodecTypes['pg/numeric@1']['input'];
      readonly stockActual: CodecTypes['pg/int4@1']['input'];
      readonly stockMinimo: CodecTypes['pg/int4@1']['input'];
    };
    readonly utilizador: {
      readonly activo: CodecTypes['pg/bool@1']['input'];
      readonly actualizadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly palavraPasse: CodecTypes['pg/text@1']['input'];
      readonly perfil: 'ADMINISTRADOR' | 'ATENDENTE';
    };
    readonly venda: {
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly total: CodecTypes['pg/numeric@1']['input'];
      readonly utilizadorId: CodecTypes['pg/int4@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Utilizador = {
    id: CodecTypes['pg/int4@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    palavraPasse: CodecTypes['pg/text@1']['output'];
    perfil: 'ADMINISTRADOR' | 'ATENDENTE';
    activo: CodecTypes['pg/bool@1']['output'];
    criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    actualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    movimentosStock: public_MovimentoStock[];
    vendas: public_Venda[];
    readonly [RelationKeys]?: 'movimentosStock' | 'vendas';
  };
  export type public_Categoria = {
    id: CodecTypes['pg/int4@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    descricao: CodecTypes['pg/text@1']['output'] | null;
    activo: CodecTypes['pg/bool@1']['output'];
    criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    actualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    produtos: public_Produto[];
    readonly [RelationKeys]?: 'produtos';
  };
  export type public_Produto = {
    id: CodecTypes['pg/int4@1']['output'];
    codigo: CodecTypes['pg/text@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    descricao: CodecTypes['pg/text@1']['output'] | null;
    categoriaId: CodecTypes['pg/int4@1']['output'];
    precoCompra: CodecTypes['pg/numeric@1']['output'];
    precoVenda: CodecTypes['pg/numeric@1']['output'];
    stockActual: CodecTypes['pg/int4@1']['output'];
    stockMinimo: CodecTypes['pg/int4@1']['output'];
    activo: CodecTypes['pg/bool@1']['output'];
    criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    actualizadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    categoria: public_Categoria;
    itensVenda: public_ItemVenda[];
    movimentosStock: public_MovimentoStock[];
    readonly [RelationKeys]?: 'categoria' | 'itensVenda' | 'movimentosStock';
  };
  export type public_Venda = {
    id: CodecTypes['pg/int4@1']['output'];
    utilizadorId: CodecTypes['pg/int4@1']['output'];
    total: CodecTypes['pg/numeric@1']['output'];
    criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    itens: public_ItemVenda[];
    utilizador: public_Utilizador;
    readonly [RelationKeys]?: 'itens' | 'utilizador';
  };
  export type public_ItemVenda = {
    id: CodecTypes['pg/int4@1']['output'];
    vendaId: CodecTypes['pg/int4@1']['output'];
    produtoId: CodecTypes['pg/int4@1']['output'];
    quantidade: CodecTypes['pg/int4@1']['output'];
    precoUnitario: CodecTypes['pg/numeric@1']['output'];
    subtotal: CodecTypes['pg/numeric@1']['output'];
    produto: public_Produto;
    venda: public_Venda;
    readonly [RelationKeys]?: 'produto' | 'venda';
  };
  export type public_MovimentoStock = {
    id: CodecTypes['pg/int4@1']['output'];
    produtoId: CodecTypes['pg/int4@1']['output'];
    utilizadorId: CodecTypes['pg/int4@1']['output'];
    tipo: 'ENTRADA' | 'SAIDA' | 'AJUSTE';
    quantidade: CodecTypes['pg/int4@1']['output'];
    stockAnterior: CodecTypes['pg/int4@1']['output'];
    stockPosterior: CodecTypes['pg/int4@1']['output'];
    motivo: CodecTypes['pg/text@1']['output'] | null;
    criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    produto: public_Produto;
    utilizador: public_Utilizador;
    readonly [RelationKeys]?: 'produto' | 'utilizador';
  };
}

export declare const models: {
  public: {
    Utilizador: Models.public_Utilizador;
    Categoria: Models.public_Categoria;
    Produto: Models.public_Produto;
    Venda: Models.public_Venda;
    ItemVenda: Models.public_ItemVenda;
    MovimentoStock: Models.public_MovimentoStock;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly categoria: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descricao: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly activo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly actualizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['nome'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly itemVenda: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly vendaId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly produtoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly quantidade: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly precoUnitario: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly subtotal: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'itemVenda_vendaId_idx_6df73982';
                  readonly prefix: 'itemVenda_vendaId_idx';
                  readonly columns: readonly ['vendaId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'itemVenda_produtoId_idx_eb62fdb9';
                  readonly prefix: 'itemVenda_produtoId_idx';
                  readonly columns: readonly ['produtoId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'itemVenda';
                    readonly columns: readonly ['vendaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'venda';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'itemVenda';
                    readonly columns: readonly ['produtoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'produto';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly movimentoStock: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly produtoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly utilizadorId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly tipo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quantidade: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly stockAnterior: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly stockPosterior: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly motivo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'movimentoStock_produtoId_idx_eb62fdb9';
                  readonly prefix: 'movimentoStock_produtoId_idx';
                  readonly columns: readonly ['produtoId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'movimentoStock_utilizadorId_idx_9b27b684';
                  readonly prefix: 'movimentoStock_utilizadorId_idx';
                  readonly columns: readonly ['utilizadorId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'movimentoStock_tipo_idx_2cc2d1f4';
                  readonly prefix: 'movimentoStock_tipo_idx';
                  readonly columns: readonly ['tipo'];
                  readonly unique: false;
                },
                {
                  readonly name: 'movimentoStock_criadoEm_idx_f1f7cf71';
                  readonly prefix: 'movimentoStock_criadoEm_idx';
                  readonly columns: readonly ['criadoEm'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'movimentoStock';
                    readonly columns: readonly ['produtoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'produto';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'movimentoStock';
                    readonly columns: readonly ['utilizadorId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'utilizador';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly produto: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly codigo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descricao: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly categoriaId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly precoCompra: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly precoVenda: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly stockActual: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly stockMinimo: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly activo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly actualizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['codigo'] }];
              indexes: readonly [
                {
                  readonly name: 'produto_categoriaId_idx_63b46427';
                  readonly prefix: 'produto_categoriaId_idx';
                  readonly columns: readonly ['categoriaId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'produto';
                    readonly columns: readonly ['categoriaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'categoria';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly utilizador: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly palavraPasse: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly perfil: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly activo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly actualizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly venda: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly utilizadorId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly total: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'venda_utilizadorId_idx_9b27b684';
                  readonly prefix: 'venda_utilizadorId_idx';
                  readonly columns: readonly ['utilizadorId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'venda_criadoEm_idx_f1f7cf71';
                  readonly prefix: 'venda_criadoEm_idx';
                  readonly columns: readonly ['criadoEm'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'venda';
                    readonly columns: readonly ['utilizadorId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'utilizador';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly Perfil: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ADMINISTRADOR', 'ATENDENTE'];
            };
            readonly TipoMovimentoStock: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ENTRADA', 'SAIDA', 'AJUSTE'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly utilizador: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Utilizador';
    };
    readonly categoria: { readonly namespace: 'public' & NamespaceId; readonly model: 'Categoria' };
    readonly produto: { readonly namespace: 'public' & NamespaceId; readonly model: 'Produto' };
    readonly venda: { readonly namespace: 'public' & NamespaceId; readonly model: 'Venda' };
    readonly itemVenda: { readonly namespace: 'public' & NamespaceId; readonly model: 'ItemVenda' };
    readonly movimentoStock: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'MovimentoStock';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Categoria: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descricao: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly activo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly actualizadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly produtos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Produto';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['categoriaId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'categoria';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly descricao: { readonly column: 'descricao' };
                readonly activo: { readonly column: 'activo' };
                readonly criadoEm: { readonly column: 'criadoEm' };
                readonly actualizadoEm: { readonly column: 'actualizadoEm' };
              };
            };
          };
          readonly ItemVenda: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly vendaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly produtoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly quantidade: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly precoUnitario: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly subtotal: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
            };
            readonly relations: {
              readonly produto: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Produto';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['produtoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly venda: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Venda';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['vendaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'itemVenda';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly vendaId: { readonly column: 'vendaId' };
                readonly produtoId: { readonly column: 'produtoId' };
                readonly quantidade: { readonly column: 'quantidade' };
                readonly precoUnitario: { readonly column: 'precoUnitario' };
                readonly subtotal: { readonly column: 'subtotal' };
              };
            };
          };
          readonly MovimentoStock: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly produtoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly utilizadorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tipo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quantidade: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly stockAnterior: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly stockPosterior: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly motivo: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly produto: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Produto';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['produtoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly utilizador: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Utilizador';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['utilizadorId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'movimentoStock';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly produtoId: { readonly column: 'produtoId' };
                readonly utilizadorId: { readonly column: 'utilizadorId' };
                readonly tipo: { readonly column: 'tipo' };
                readonly quantidade: { readonly column: 'quantidade' };
                readonly stockAnterior: { readonly column: 'stockAnterior' };
                readonly stockPosterior: { readonly column: 'stockPosterior' };
                readonly motivo: { readonly column: 'motivo' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
          readonly Produto: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly codigo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descricao: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly categoriaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly precoCompra: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly precoVenda: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly stockActual: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly stockMinimo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly activo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly actualizadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly categoria: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Categoria';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['categoriaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly itensVenda: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ItemVenda';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['produtoId'];
                };
              };
              readonly movimentosStock: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'MovimentoStock';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['produtoId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'produto';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly codigo: { readonly column: 'codigo' };
                readonly nome: { readonly column: 'nome' };
                readonly descricao: { readonly column: 'descricao' };
                readonly categoriaId: { readonly column: 'categoriaId' };
                readonly precoCompra: { readonly column: 'precoCompra' };
                readonly precoVenda: { readonly column: 'precoVenda' };
                readonly stockActual: { readonly column: 'stockActual' };
                readonly stockMinimo: { readonly column: 'stockMinimo' };
                readonly activo: { readonly column: 'activo' };
                readonly criadoEm: { readonly column: 'criadoEm' };
                readonly actualizadoEm: { readonly column: 'actualizadoEm' };
              };
            };
          };
          readonly Utilizador: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly palavraPasse: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly perfil: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly activo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly actualizadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly movimentosStock: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'MovimentoStock';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['utilizadorId'];
                };
              };
              readonly vendas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Venda';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['utilizadorId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'utilizador';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly email: { readonly column: 'email' };
                readonly palavraPasse: { readonly column: 'palavraPasse' };
                readonly perfil: { readonly column: 'perfil' };
                readonly activo: { readonly column: 'activo' };
                readonly criadoEm: { readonly column: 'criadoEm' };
                readonly actualizadoEm: { readonly column: 'actualizadoEm' };
              };
            };
          };
          readonly Venda: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly utilizadorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly total: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly itens: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ItemVenda';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['vendaId'];
                };
              };
              readonly utilizador: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Utilizador';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['utilizadorId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'venda';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly utilizadorId: { readonly column: 'utilizadorId' };
                readonly total: { readonly column: 'total' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
        };
        readonly enum: {
          readonly Perfil: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ADMINISTRADOR'; readonly value: 'ADMINISTRADOR' },
              { readonly name: 'ATENDENTE'; readonly value: 'ATENDENTE' },
            ];
          };
          readonly TipoMovimentoStock: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ENTRADA'; readonly value: 'ENTRADA' },
              { readonly name: 'SAIDA'; readonly value: 'SAIDA' },
              { readonly name: 'AJUSTE'; readonly value: 'AJUSTE' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'categoria';
            readonly column: 'actualizadoEm';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'produto';
            readonly column: 'actualizadoEm';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'utilizador';
            readonly column: 'actualizadoEm';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
